### YamlMime:ManagedReference
items:
- uid: Recycle.Api.Settings.SmtpSettings
  commentId: T:Recycle.Api.Settings.SmtpSettings
  id: SmtpSettings
  parent: Recycle.Api.Settings
  children:
  - Recycle.Api.Settings.SmtpSettings.Host
  - Recycle.Api.Settings.SmtpSettings.Password
  - Recycle.Api.Settings.SmtpSettings.Port
  - Recycle.Api.Settings.SmtpSettings.Sender
  - Recycle.Api.Settings.SmtpSettings.UserName
  langs:
  - csharp
  - vb
  name: SmtpSettings
  nameWithType: SmtpSettings
  fullName: Recycle.Api.Settings.SmtpSettings
  type: Class
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: SmtpSettings
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 2
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public class SmtpSettings
    content.vb: Public Class SmtpSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Recycle.Api.Settings.SmtpSettings.Host
  commentId: P:Recycle.Api.Settings.SmtpSettings.Host
  id: Host
  parent: Recycle.Api.Settings.SmtpSettings
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: SmtpSettings.Host
  fullName: Recycle.Api.Settings.SmtpSettings.Host
  type: Property
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: Host
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 4
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public string Host { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Host As String
  overload: Recycle.Api.Settings.SmtpSettings.Host*
- uid: Recycle.Api.Settings.SmtpSettings.Port
  commentId: P:Recycle.Api.Settings.SmtpSettings.Port
  id: Port
  parent: Recycle.Api.Settings.SmtpSettings
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: SmtpSettings.Port
  fullName: Recycle.Api.Settings.SmtpSettings.Port
  type: Property
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: Port
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 6
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Port As Integer
  overload: Recycle.Api.Settings.SmtpSettings.Port*
- uid: Recycle.Api.Settings.SmtpSettings.UserName
  commentId: P:Recycle.Api.Settings.SmtpSettings.UserName
  id: UserName
  parent: Recycle.Api.Settings.SmtpSettings
  langs:
  - csharp
  - vb
  name: UserName
  nameWithType: SmtpSettings.UserName
  fullName: Recycle.Api.Settings.SmtpSettings.UserName
  type: Property
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: UserName
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 8
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public string UserName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UserName As String
  overload: Recycle.Api.Settings.SmtpSettings.UserName*
- uid: Recycle.Api.Settings.SmtpSettings.Password
  commentId: P:Recycle.Api.Settings.SmtpSettings.Password
  id: Password
  parent: Recycle.Api.Settings.SmtpSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: SmtpSettings.Password
  fullName: Recycle.Api.Settings.SmtpSettings.Password
  type: Property
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: Password
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 10
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: Recycle.Api.Settings.SmtpSettings.Password*
- uid: Recycle.Api.Settings.SmtpSettings.Sender
  commentId: P:Recycle.Api.Settings.SmtpSettings.Sender
  id: Sender
  parent: Recycle.Api.Settings.SmtpSettings
  langs:
  - csharp
  - vb
  name: Sender
  nameWithType: SmtpSettings.Sender
  fullName: Recycle.Api.Settings.SmtpSettings.Sender
  type: Property
  source:
    remote:
      path: Recycle/Settings/SmtpSettings.cs
      branch: dev
      repo: https://github.com/ElaDusova/RecycleApp.git
    id: Sender
    path: ../Recycle/Settings/SmtpSettings.cs
    startLine: 12
  assemblies:
  - Recycle.Api
  namespace: Recycle.Api.Settings
  syntax:
    content: public string Sender { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Sender As String
  overload: Recycle.Api.Settings.SmtpSettings.Sender*
references:
- uid: Recycle.Api.Settings
  commentId: N:Recycle.Api.Settings
  href: Recycle.html
  name: Recycle.Api.Settings
  nameWithType: Recycle.Api.Settings
  fullName: Recycle.Api.Settings
  spec.csharp:
  - uid: Recycle
    name: Recycle
    href: Recycle.html
  - name: .
  - uid: Recycle.Api
    name: Api
    href: Recycle.Api.html
  - name: .
  - uid: Recycle.Api.Settings
    name: Settings
    href: Recycle.Api.Settings.html
  spec.vb:
  - uid: Recycle
    name: Recycle
    href: Recycle.html
  - name: .
  - uid: Recycle.Api
    name: Api
    href: Recycle.Api.html
  - name: .
  - uid: Recycle.Api.Settings
    name: Settings
    href: Recycle.Api.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Recycle.Api.Settings.SmtpSettings.Host*
  commentId: Overload:Recycle.Api.Settings.SmtpSettings.Host
  href: Recycle.Api.Settings.SmtpSettings.html#Recycle_Api_Settings_SmtpSettings_Host
  name: Host
  nameWithType: SmtpSettings.Host
  fullName: Recycle.Api.Settings.SmtpSettings.Host
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Recycle.Api.Settings.SmtpSettings.Port*
  commentId: Overload:Recycle.Api.Settings.SmtpSettings.Port
  href: Recycle.Api.Settings.SmtpSettings.html#Recycle_Api_Settings_SmtpSettings_Port
  name: Port
  nameWithType: SmtpSettings.Port
  fullName: Recycle.Api.Settings.SmtpSettings.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Recycle.Api.Settings.SmtpSettings.UserName*
  commentId: Overload:Recycle.Api.Settings.SmtpSettings.UserName
  href: Recycle.Api.Settings.SmtpSettings.html#Recycle_Api_Settings_SmtpSettings_UserName
  name: UserName
  nameWithType: SmtpSettings.UserName
  fullName: Recycle.Api.Settings.SmtpSettings.UserName
- uid: Recycle.Api.Settings.SmtpSettings.Password*
  commentId: Overload:Recycle.Api.Settings.SmtpSettings.Password
  href: Recycle.Api.Settings.SmtpSettings.html#Recycle_Api_Settings_SmtpSettings_Password
  name: Password
  nameWithType: SmtpSettings.Password
  fullName: Recycle.Api.Settings.SmtpSettings.Password
- uid: Recycle.Api.Settings.SmtpSettings.Sender*
  commentId: Overload:Recycle.Api.Settings.SmtpSettings.Sender
  href: Recycle.Api.Settings.SmtpSettings.html#Recycle_Api_Settings_SmtpSettings_Sender
  name: Sender
  nameWithType: SmtpSettings.Sender
  fullName: Recycle.Api.Settings.SmtpSettings.Sender
